"""
Synthetic plate (rice / chicken / asparagus) + matching 8x8 ToF grid.

  python tools/mock_plate.py --header firmware/wokwi_sim/mock_data.h   # for the Wokwi sketch
  python tools/mock_plate.py --post http://127.0.0.1:8000 [--key SECRET]  # test the server directly

The ToF grid averages true heights over each zone's footprint (like the real sensor),
so thin items such as asparagus are visibly blurred - that is the honest 8x8 limitation.
"""
import argparse
import json
import math

import cv2
import numpy as np

W, H, FX, FY, CX, CY = 640, 480, 628.0, 628.0, 320.0, 240.0
TOF_FOV, TABLE_MM = 45.0, 400
# label, centre, semi-axes, angle, BGR colour, height mm
OBJECTS = [
    ("rice", (230, 260), (95, 80), 0, (235, 235, 235), 28),
    ("chicken", (400, 220), (85, 60), 20, (50, 100, 160), 22),
    ("asparagus", (420, 370), (110, 22), -15, (60, 150, 70), 12),
]


def render():
    img = np.full((H, W, 3), 40, np.uint8)
    hmap = np.zeros((H, W), np.float32)
    masks = {}
    for label, c, ax, ang, bgr, hh in OBJECTS:
        m = np.zeros((H, W), np.uint8)
        cv2.ellipse(m, c, ax, ang, 0, 360, 1, -1)
        img[m > 0] = bgr
        hmap[m > 0] = hh
        masks[label] = (int(m.sum()), hh)
    return img, hmap, masks


def depth_grid(hmap, rng):
    edges = np.tan(np.radians((np.arange(9) / 8 - 0.5) * TOF_FOV))
    xs = (CX + FX * edges).round().astype(int)
    ys = (CY + FY * edges).round().astype(int)
    out = np.zeros((8, 8))
    for r in range(8):
        for c in range(8):
            x0, x1 = max(xs[c], 0), min(xs[c + 1], W)
            y0, y1 = max(ys[r], 0), min(ys[r + 1], H)
            box = hmap[y0:y1, x0:x1]
            out[r, c] = TABLE_MM - (box.mean() if box.size else 0) + rng.normal(0, 1.5)
    return out.round().astype(int)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--header")
    ap.add_argument("--post")
    ap.add_argument("--key", default="")
    a = ap.parse_args()

    rng = np.random.default_rng(7)
    img, hmap, masks = render()
    depth = depth_grid(hmap, rng)
    ok, jpg = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, 75])
    jpg = jpg.tobytes()
    print(f"JPEG {len(jpg)/1024:.1f} KiB; depth (mm):\n{depth}")

    if a.header:
        body = ",".join(str(b) for b in jpg)
        with open(a.header, "w") as f:
            f.write("// generated by tools/mock_plate.py\n#pragma once\n#include <Arduino.h>\n")
            f.write(f"const size_t MOCK_JPEG_LEN = {len(jpg)};\n")
            f.write(f"const uint8_t MOCK_JPEG[] PROGMEM = {{{body}}};\n")
            f.write(f"const int MOCK_DEPTH_MM[64] = {{{','.join(map(str, depth.ravel()))}}};\n")
        print("wrote", a.header)

    if a.post:
        import requests

        r = requests.post(
            a.post.rstrip("/") + "/analyze-plate",
            files={"image": ("frame.jpg", jpg, "image/jpeg")},
            data={"depth": json.dumps(depth.ravel().tolist())},
            headers={"X-API-Key": a.key, "ngrok-skip-browser-warning": "1"},
            timeout=30,
        )
        print("HTTP", r.status_code)
        try:
            body = r.json()
        except ValueError:
            raise SystemExit(f"server did not return JSON (check the uvicorn terminal for the traceback):\n{r.text[:500]}")
        print(json.dumps(body, indent=2))
        if r.status_code != 200:
            raise SystemExit(1)
        f_cm = FX  # approx footprint check: area_px * (z/f)^2 * h, z ~ table - h
        print("\napprox ground truth (flat-top prisms):")
        for label, (px, hh) in masks.items():
            z = (TABLE_MM - hh) / 10
            print(f"  {label:10s} ~{px * (z / f_cm) ** 2 * hh / 10:.0f} mL  (h={hh/10:.1f} cm)")


if __name__ == "__main__":
    main()
